apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: country-info
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: countryinfo
  MYSQL_USER: countryuser
  MYSQL_PASSWORD: countrypassword
